version: '3'
services:
  rp:
    build: ../nginx/dev
    network_mode: "host"
  neo4j:
    image: "neo4j:3.5"
    environment:
      - "NEO4J_AUTH=none"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - "$HOME/neo4j/data:/data"